import { serve } from 'https://deno.land/std@0.177.0/http/server.ts'
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2'
// Temporarily remove local import and define headers inline
// import { corsHeaders } from '../_shared/cors.ts'

// Define CORS headers directly for testing
const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
  'Access-Control-Allow-Methods': 'POST, GET, OPTIONS, PUT, DELETE', // Ensure OPTIONS is included
}

console.log(`Function "create-invitation" up and running!`)

interface InvitationPayload {
  capsule_id: string;
  invitee_email?: string;
  message?: string;
}

serve(async (req) => {
  // Handle CORS preflight request
  if (req.method === 'OPTIONS') {
    return new Response('ok', { headers: corsHeaders })
  }

  try {
    const payload: InvitationPayload = await req.json()
    const { capsule_id, invitee_email, message } = payload

    if (!capsule_id) {
      throw new Error("Missing 'capsule_id' in request body")
    }

    // Create Supabase client with Auth context
    const supabaseClient = createClient(
      Deno.env.get('SUPABASE_URL') ?? '',
      Deno.env.get('SUPABASE_ANON_KEY') ?? '',
      { global: { headers: { Authorization: req.headers.get('Authorization')! } } }
    )

    // Get the authenticated user
    const { data: { user }, error: userError } = await supabaseClient.auth.getUser()
    if (userError || !user) {
      console.error('User error:', userError)
      return new Response(JSON.stringify({ error: 'User not authenticated' }), {
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
        status: 401,
      })
    }
    const inviter_user_id = user.id

    // 1. Verify the inviter owns the capsule
    const { data: capsuleData, error: capsuleError } = await supabaseClient
      .from('capsulas')
      .select('id')
      .eq('id', capsule_id)
      .eq('usuario_id', inviter_user_id)
      .maybeSingle() // Use maybeSingle to handle null case gracefully

    if (capsuleError) {
      console.error('Capsule check error:', capsuleError)
      throw new Error(`Failed to verify capsule ownership: ${capsuleError.message}`)
    }
    if (!capsuleData) {
      return new Response(JSON.stringify({ error: 'Capsule not found or user does not own it' }), {
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
        status: 403, // Forbidden
      })
    }

    // 2. Insert the invitation record
    // The share_token will be generated by the database default value
    const { data: invitationData, error: insertError } = await supabaseClient
      .from('capsule_invitations')
      .insert({
        capsule_id: capsule_id,
        inviter_user_id: inviter_user_id,
        invitee_email: invitee_email,
        message: message,
        // status defaults to 'pending'
        // share_token defaults to gen_random_uuid()::text or similar
      })
      .select('share_token') // Select the generated token
      .single() // Expecting a single row back

    if (insertError) {
      console.error('Invitation insert error:', insertError)
      // Handle potential unique constraint violation if needed, though token should be unique
      throw new Error(`Failed to create invitation: ${insertError.message}`)
    }

    if (!invitationData || !invitationData.share_token) {
        console.error('Invitation data or share_token missing after insert')
        throw new Error('Failed to retrieve share_token after creating invitation')
    }

    const share_token = invitationData.share_token;

    // 3. (Optional) Send email if invitee_email is provided
    // Add email sending logic here using Supabase Auth admin or a third-party service
    // Example placeholder:
    if (invitee_email) {
      console.log(`Placeholder: Send email invitation to ${invitee_email} with token ${share_token}`)
      // Consider using a Supabase Edge Function or a dedicated email service
    }

    // 4. Return the share_token
    return new Response(JSON.stringify({ share_token }), {
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      status: 200,
    })

  } catch (error) {
    console.error('Error in create-invitation function:', error)
    return new Response(JSON.stringify({ error: error.message }), {
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      status: 500,
    })
  }
})
